// <auto-generated />
namespace MovieNight.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieFansRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieFansRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202104021010569_MovieFansRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
